shark:
  name: "鲨鱼"
  image_path: "shark.png"
  speed: 0.5
  attack: 8
  health: 10
  value: 10
  size:
    width: 100
    height: 100

tuna:
  name: "龙鱼"
  image_path: "tuna.png"
  speed: 1
  attack: 3
  health: 5
  value: 20
  size:
    width: 50
    height: 50

goldfish:
  name: "金鱼"
  image_path: "goldfish.png"
  speed: 0.2
  attack: 0
  health: 5
  value: 5
  size:
    width: 25
    height: 25